### PR TITLE
v0.6.0-rc9 

### PR DESCRIPTION
**Pull request by siskai**
update v3 bundle to stable branch
add enable full header encryption for v2 and v3

### CODE REVIEW

**Comment by ozyb** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，邮件已收到。我将尽快给您回复。

**Comment by lucktu** [comment]
Sorry, due to my compilation environment problems, can not verify whether your code is normal, it may take a while to pass, forgive me! 

Thank you for your code!

In addition, it is not recommended to use official code directly, and it is best to keep it in a state of no problem.

**Comment by ozyb** [comment]
> 将v3 包更新到稳定分支 添加为 v2 和 v3 启用完整的标头加密

提交少了 一个cpp文件，麻烦补充一下

`  CMake Error at CMakeLists.txt:81 (add_library):
    Cannot find source file:

      src/mainp/n2n_v3c/edge_management.c

    Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
    .hxx .in .txx


  CMake Error: CMake can not determine linker language for target: edge_v3`

**Comment by ozyb** [comment]
> update v3 bundle to stable branch add enable full header encryption for v2 and v3


提交少了 一个cpp文件，麻烦补充一下

```
 CMake Error at CMakeLists.txt:81 (add_library):
    Cannot find source file:

      src/mainp/n2n_v3c/edge_management.c

    Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
    .hxx .in .txx

  CMake Error: CMake can not determine linker language for target: edge_v3
```

**Comment by lucktu** [comment]
Normal. no refills
Thanks!

**Pull request merged**
